#!/bin/bash

# 󰕿         󰖀  󰕾         󰝟  󰝟  󰸈 
#     vol > 66
#  󰕾    66 > vol > 33
#      33 > vol > 0
#      vol == 0 | mute
#  󱄡   获取信息错误


# 获取音量
get_volume() {
    volume_str=$(amixer sget "Master" | grep 'Front Left:' | awk -F'[][]' '{ print $2 }')
    echo "${volume_str%\%}"
}

# 获取静音状态
get_muted() {
    echo $(amixer sget "Master" | grep -E 'Left.*\[' | awk -F'[][]' '{print $4 }')
}

# return icon && vol, 显示在状态栏(dwmblocks)
res() {
    volume=$(get_volume)
    vol=$(($volume))
    muted=$(get_muted)

    if [ "$muted" == "on" ]; then
        if [ $vol -gt 66 ]; then
            icon=" "
        elif [ $vol -gt 33 ] ; then
            icon="󰕾 "
        elif [ $vol -gt 0 ]; then
            icon=" "
        elif [ $vol -eq 0 ]; then
            icon=" "
        fi
    elif [ "$muted" == "off" ]; then 
        icon=" "
    else
        icon="󱄡"
    fi
    
    echo "${icon}${vol}%"
}

# 音量 +5%, 
add() {
    amixer sset "Master" 5%+ >> /home/cofon/log
    pkill -RTMIN+10 dwmblocks
}

# 音量 -5%
sub() {
    amixer sset "Master" 5%- >> /home/cofon/log
    pkill -RTMIN+10 dwmblocks
}

# 静音切换
mute() {
    amixer sset "Master" toggle >> /home/cofon/log
    pkill -RTMIN+10 dwmblocks
}


# 如果没有参数，执行函数 res，退出脚本，code：0
if [ "$1" == "" ]; then 
    res
    exit 0
fi
 
# 检查传入的参数是否为已声明的函数名，是：调用函数，不是：写入日志
if [[ $(type -t "$1") == function ]]; then
    "$1"  
else
    echo "假装已经写入日志"
fi

