#!/bin/bash

# brightnessctl max == 937
#brightnessctl set 500 设置亮度为 500
#Sets brightness to 500.

#brightnessctl set 50% 设置亮度为 最大亮度值的50%
#Sets brightness to 50% of the maximum.

#brightnessctl set -50 设置亮度为 当前亮度值50-
#Subtracts 50 from the current brightness.

#brightnessctl set +50 设置亮度为 当前亮度值+50
#Adds 50 to the current brightness.

#brightnessctl set 10%- 设置亮度为 当前亮度值-max*10%
#Subtracts 10% of the maximum from the current brightness.

#brightnessctl set +10% 设置亮度为 当前亮度值+max*10%
#Adds 10% of the maximum to the current brightness.

# 如果 $1 == “up"  , 亮度 +5%
# 如果 $1 == "down", 亮度 -5%
# 如果没有参数, 亮度 == 50%
if [ "$1" = "up" ]; then
    brightnessctl set +5%
elif [ "$1" = "down" ]; then
    brightnessctl set 5%-
else 
    brightnessctl set 50%
fi

