#!/bin/bash

# 获取电池状态信息
# 三种状态
# 电量 =100% 接入电源 -->  Battery 0: Not charging, 100%
# 电量 <100% 接入电源 -->  Battery 0: Charging, 89%, 00:22:03 until charged  需要充电时长
# 电量 <100% 不接电源 -->  Battery 0: Discharging, 90%, 01:56:17 remaining   电池可用时长
battery_info=$(acpi -b)

# 提取电池状态、是否正在充电和电池电量
charging_state=$(echo "$battery_info" | awk -F', ' '{print $1}' | awk -F ":"  '{print $2}' | sed "s/^ *//")
battery_percentage=$(echo "$battery_info" | grep -o '[0-9]*%' |  grep -o '[0-9]\+')

# 电池电量 取后缀 转数字
pe=$((battery_percentage))

if [ "${charging_state}" = "Not charging" ]; then 
    icon="F "
elif [ "${charging_state}" = "Charging" ]; then 
    icon="C "
elif [ "${charging_state}" = "Discharging" ]; then
    icon="D "
else 
    icon="E "
fi

# 输出提取的信息
#echo "充电状态: $charging_state"
#echo "电池电量: $battery_percentage"
echo "${icon}${battery_percentage}%"
